name <- "CepespVis"

shinyUI(function(request){

  fluidPage(

  includeCSS("www/simplex.min.css"),

  tags$head(
  	HTML('<!-- Global site tag (gtag.js) - Google Analytics -->
			<script async src="https://www.googletagmanager.com/gtag/js?id=UA-109541745-2"></script>
			<script>
			  window.dataLayer = window.dataLayer || [];
			  function gtag(){dataLayer.push(arguments);}
			  gtag("js", new Date());

			  gtag("config", "UA-109541745-2");
			</script>')
  ), 

  tags$head(
  	HTML('<title>CepespVis</title>
		 <meta charset="utf-8">
		 <meta name="viewport" content="width=device-width, initial-scale=1.0" />
		        <!-- COMMON TAGS -->
		        <!-- Search Engine -->
		 <meta name="description" content="CepespVis é um portal com visualização de dados eleitorais, desenvolvido para o 1º DESAFIO DO CEPESP: DECIFRANDO AS ELEIÇÕES." />')
  ),

  tags$head(
      tags$link(rel="shortcut icon", href="gvicon.ico")
   ),

   tags$head(
      tags$link(rel = "stylesheet", href = "https://fonts.googleapis.com/css?family=Roboto:400,700")
   ),

   includeCSS("www/style.css"),

   navbarPage(

    collapsible = T,

    id = "main_page",
    

    #theme = shinytheme("simplex"),
    #theme = shinytheme("lumen"),
  
    #name,

    windowTitle = name,

    div(
        img(src = "gv_logo.png",
            height = "30px",  
            style = "margin:0"
        )
      ),
    
    tabPanel(id = "home_page","Início", icon = icon("home"),
    	HTML('<iframe src="https://paeselab.com/inicio/" frameborder="0" style="overflow:hidden;overflow-x:hidden;overflow-y:hidden;height:100%;width:100%;position:absolute;top:0px;left:0px;right:0px;bottom:0px" height="100%" width="100%"></iframe>')
    	),

    navbarMenu("Eleições Municipais",icon = icon("building"), 
        tabPanel(id = "prefeito_tab",
                 "Prefeito",
                 h4("Eleições Municipais para Prefeito", align = "center"),
                 sidebarLayout(
                   sidebarPanel(width = 3,
                                sliderInput('ano_mun_prefeito',"Ano:",
                                            min = 2000,
                                            max = 2016,
                                            value = 2016,
                                            step = 4,
                                            sep = ""),
                                #radioButtons('pref_turno', "Turno",
                                #             choices = c("1º Turno" = 'turno_1',
                                #                         "2º Turno" = 'turno_2')),
                                awesomeRadio(inputId = 'pref_turno', label = "Turno: ",
                                			 choices = c("1º Turno" = 'turno_1',
                                			 			 "2º Turno" = 'turno_2')),
                                selectInput('escolhe_est_prefeito', "Estado",
                                            unique(tse_data_ui_mun$NOME_UF),
                                            selected = "São Paulo"),
                                selectInput('escolhe_mun_prefeito', "Município",
                                            unique(tse_data_ui_mun$NOME_MUNICIPIO),
                                            selected = "SÃO PAULO"),
                                bookmarkButton(id = "bookmark1",
                                               label = "Compartilhe...",
                                               icon = icon("share-alt"),
                                               title = "Compartilhe essa informação!")),
                   mainPanel(width = 9,
                             tabsetPanel(type = 'tabs',
                                 tabPanel("Distribuição dos Votos", icon = icon("database"), id = "pref_dist_votos",
                                          br(),
                                          uiOutput('tree_prefeito_final') %>% withSpinner(type = 6, color = "#555555")
                                          ),
                                 tabPanel("Votação dos Candidatos", icon = icon("bar-chart"), id = "pref_vot_candi",
                                          br(),
                                          plotlyOutput("grafico_prefeitos_candidatos") %>% withSpinner(type = 6, color = "#555555"))
                                 ))
                 )),
        tabPanel(id = "vereador_tab", "Vereador",
                 h4("Eleições Municipais para Vereador", align = "center"),
                 sidebarLayout(
                   sidebarPanel(width = 3,
                                sliderInput('ano_mun_vereador',"Ano:",
                                            min = 2000,
                                            max = 2016,
                                            value = 2016,
                                            step = 4,
                                            sep = ""),
                                selectInput('escolhe_est_vereador', "Estado",
                                            unique(tse_data_ui_mun$NOME_UF),
                                            selected = "São Paulo"),
                                selectInput('escolhe_mun_vereador', "Município",
                                            unique(tse_data_ui_mun$NOME_MUNICIPIO),
                                            selected = "SÃO PAULO"),
                                bookmarkButton(id = "bookmark2",
                                               label = "Compartilhe...",
                                               icon = icon("share-alt"),
                                               title = "Compartilhe essa informação!")),
                   mainPanel(width = 9,
                             tabsetPanel(type = 'tabs',
                                         tabPanel("Distribuição dos Votos",icon = icon("database"), id = "vereador_dist_votos",
                                                  br(),
                                                  uiOutput('tree_vereador_final') %>% withSpinner(type = 6, color = "#555555")),
                                         tabPanel("Votação dos Eleitos", icon = icon("bar-chart"), id = "vereador_vot_eleitos",
                                                  br(),
                                                  plotlyOutput("grafico_vereadores_eleitos") %>% withSpinner(type = 6, color = "#555555")),
                                         tabPanel("Quociente Eleitoral", icon = icon("cog"), id = "vereador_qp_qe",
                                                  div(h3(textOutput("qe_vereador")), align = "center", style = "color:black;"),
                                                  #div(h5(textOutput("qp_vereador")), align = "center", style = "color:black;"),
                                                  plotlyOutput("grafico_quociente_partidos") %>% withSpinner(type = 6, color = "#555555"))
                                         ))
                 ))),
    
    navbarMenu("Eleições Gerais", icon = icon("bank"),
        tabPanel("Deputado Estadual", id = 'tab_deputado_estadual',
             h4("Eleições Gerais para Deputado Estadual", align = "center"), 
                 tabsetPanel(type = 'tabs', id = 'tab_set_deputados_estaduais',
                       tabPanel("Estado", id = 'tab_deputado_estadual_estado',
                                  br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_est_dep_est', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     selectInput('escolhe_est_dep_est_est', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     bookmarkButton(id = "bookmark3",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9,
                                                tabsetPanel(type = 'tabs',
                                                            tabPanel("Distribuição dos Votos",icon = icon("database"), id = "dep_est_dist_votos_est",
                                                                     br(),
                                                                     uiOutput("tree_dep_est_final_est") %>% withSpinner(type = 6, color = "#555555")),
                                                            tabPanel("Votação dos Eleitos pela UF", icon = icon("bar-chart"), id = "dep_est_eleitos_est",
                                                                   br(),
                                                                     plotlyOutput("grafico_dep_est_eleitos_est") %>% withSpinner(type = 6, color = "#555555"))
                                                            )))),
                       tabPanel("Municípios", id = 'tab_deputado_estadual_municipio',
                                     br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_mun_dep_est', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     selectInput('escolhe_est_dep_est', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     selectInput('escolhe_cand_dep_est', "Candidato:",
                                                                  choices = NULL),
                                                     #radioButtons('dep_est_map_choice_mun', "Representação:",
                                                     #              choices = c("Qual a origem dos votos?" = 'orig_vot',
                                                     #                          "Representação dos votos por município" = 'rep_vot'),
                                                     #              selected = "rep_vot"),
                                                     awesomeRadio(inputId = 'dep_est_map_choice_mun', label = "Representação:",
                                                     			  	choices =  c("Percentual de votos por município" = 'rep_vot',
                                                     			  				 "Qual a origem dos votos?" = 'orig_vot')),
                                                     bookmarkButton(id = "bookmark4",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                tabsetPanel(type = 'tabs',
                                                        tabPanel("Mapa das Eleições", icon = icon("map"), br(),
                                                              div(h5(textOutput("titulo_mapa_dep_est_mun")), align = "center", style = "color:black;"),
                                                              leafletOutput("mapa_dep_est_mun") %>% withSpinner(type = 6, color = "#555555")
                                                          ),
                                                        tabPanel("Tabela das Eleições", icon = icon("table"),
                                                              div(h5(textOutput("titulo_tab_dep_est_mun")), align = "center", style = "color:black;"),
                                                              formattableOutput("tab_dep_est_mun") %>% withSpinner(type = 6, color = "#555555")
                                                          )
                                                  )
                                                  
                                        ))),
                             tabPanel("Microrregiões", id = 'tab_deputado_estadual_microrregiao',
                                      br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_micro_dep_est', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     selectInput('escolhe_est_dep_est_micro', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     selectInput('escolhe_cand_dep_est_micro', "Candidato:",
                                                                  choices = NULL),
                                                     #radioButtons('dep_est_map_choice_micro', "Representação:",
                                                     #              choices = c("Qual a origem dos votos?" = 'orig_vot',
                                                     #                          "Representação dos votos por microrregião" = 'rep_vot'),
                                                     #              selected = 'rep_vot'),
                                                     awesomeRadio(inputId = 'dep_est_map_choice_micro', label = "Representação:",
                                                     			  	choices =  c("Percentual de votos por município" = 'rep_vot',
                                                     			  				 "Qual a origem dos votos?" = 'orig_vot')),
                                                     bookmarkButton(id = "bookmark5",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                tabsetPanel(type = 'tabs',
                                                        tabPanel("Mapa das Eleições", icon = icon("map"), br(),
                                                              div(h5(textOutput("titulo_mapa_dep_est_micro")), align = "center", style = "color:black;"),
                                                              leafletOutput("mapa_dep_est_micro") %>% withSpinner(type = 6, color = "#555555")
                                                          ),
                                                        tabPanel("Tabela das Eleições", icon = icon("table"),
                                                              div(h5(textOutput("titulo_tab_dep_est_micro")), align = "center", style = "color:black;"),
                                                              formattableOutput("tab_dep_est_micro") %>% withSpinner(type = 6, color = "#555555")
                                                          )
                                                  )
                                                  
                                        ))),
                             tabPanel("Mesorregiões", id = 'tab_deputado_estadual_mesorregiao',
                                      br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_meso_dep_est', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     selectInput('escolhe_est_dep_est_meso', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     selectInput('escolhe_cand_dep_est_meso', "Candidato:",
                                                                  choices = NULL),
                                                     #radioButtons('dep_est_map_choice_meso', "Representação:",
                                                     #              choices = c("Qual a origem dos votos?" = 'orig_vot',
                                                     #                          "Representação dos votos por mesorregião" = 'rep_vot'),
                                                     #              selected = 'rep_vot'),
                                                     awesomeRadio(inputId = 'dep_est_map_choice_meso', label = "Representação:",
                                                     			  	choices =  c("Percentual de votos por município" = 'rep_vot',
                                                     			  				 "Qual a origem dos votos?" = 'orig_vot')),
                                                     bookmarkButton(id = "bookmark6",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                tabsetPanel(type = 'tabs',
                                                        tabPanel("Mapa das Eleições", icon = icon("map"), br(),
                                                              div(h5(textOutput("titulo_mapa_dep_est_meso")), align = "center", style = "color:black;"),
                                                              leafletOutput("mapa_dep_est_meso") %>% withSpinner(type = 6, color = "#555555")
                                                          ),
                                                        tabPanel("Tabela das Eleições", icon = icon("table"),
                                                              div(h5(textOutput("titulo_tab_dep_est_meso")), align = "center", style = "color:black;"),
                                                              formattableOutput("tab_dep_est_meso") %>% withSpinner(type = 6, color = "#555555")
                                                          )
                                                  )
                                                  
                                        )))
                             )),
        tabPanel("Senador", id = 'tab_senador',
             h4("Eleições Gerais para Senador", align = "center"), 
                 tabsetPanel(type = 'tabs', id = 'tab_set_senadores',
                       tabPanel("Estado", id = 'tab_senador_estado',
                                  br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_senador_est', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     selectInput('escolhe_est_senador_est', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     bookmarkButton(id = "bookmark7",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9,
                                                tabsetPanel(type = 'tabs',
                                                            tabPanel("Distribuição dos Votos",icon = icon("database"),
                                                                     br(),
                                                                     uiOutput("tree_senador_final_est") %>% withSpinner(type = 6, color = "#555555")),
                                                            tabPanel("Votação dos Candidatos",icon = icon("bar-chart"),
                                                                     br(),
                                                                     plotlyOutput("grafico_senadores_cand_est") %>% withSpinner(type = 6, color = "#555555"))                                                           
                                                            )))),
                       tabPanel("Municípios", id = 'tab_senador_municipio',
                                     br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_mun_senador', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     selectInput('escolhe_est_senador_mun', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     selectInput('escolhe_senador_mun', "Candidato:",
                                                                 choices = NULL),
                                                     #radioButtons('senador_choice_mun', "Representação:",
                                                     #              choices = c("Qual a origem dos votos?" = 'orig_vot',
                                                     #                          "Representação dos votos por município" = 'rep_vot'),
                                                     #              selected = 'rep_vot'),
                                                     awesomeRadio(inputId = 'senador_choice_mun', label = "Representação:",
                                                     			  	choices =  c("Percentual de votos por município" = 'rep_vot',
                                                     			  				 "Qual a origem dos votos?" = 'orig_vot')),
                                                     bookmarkButton(id = "bookmark8",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                tabsetPanel(type = 'tabs',
                                                        tabPanel("Mapa das Eleições", icon = icon("map"), br(),
                                                              div(h5(textOutput("titulo_mapa_senadores_mun")), align = "center", style = "color:black;"),
                                                              leafletOutput("mapa_senadores_mun") %>% withSpinner(type = 6, color = "#555555")
                                                          ),
                                                        tabPanel("Tabela das Eleições", icon = icon("table"),
                                                              div(h5(textOutput("titulo_tab_senadores_mun")), align = "center", style = "color:black;"),
                                                              formattableOutput("tab_senadores_mun") %>% withSpinner(type = 6, color = "#555555")
                                                          )
                                                  )
                                                  
                                        ))),
                             tabPanel("Microrregiões", id = 'tab_senador_microrregiao',
                                      br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_micro_senador', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     selectInput('escolhe_est_senador_micro', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     selectInput('escolhe_senador_micro', "Candidato:",
                                                                 choices = NULL),
                                                     #radioButtons('senador_choice_micro', "Representação:",
                                                     #              choices = c("Qual a origem dos votos?" = 'orig_vot',
                                                     #                          "Representação dos votos por microrregião" = 'rep_vot'),
                                                     #              selected = 'rep_vot'),
                                                     awesomeRadio(inputId = 'senador_choice_micro', label = "Representação:",
                                                     			  	choices =  c("Percentual de votos por município" = 'rep_vot',
                                                     			  				 "Qual a origem dos votos?" = 'orig_vot')),
                                                     bookmarkButton(id = "bookmark9",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                tabsetPanel(type = 'tabs',
                                                        tabPanel("Mapa das Eleições", icon = icon("map"), br(),
                                                              div(h5(textOutput("titulo_mapa_senadores_micro")), align = "center", style = "color:black;"),
                                                              leafletOutput("mapa_senadores_micro") %>% withSpinner(type = 6, color = "#555555")
                                                          ),
                                                        tabPanel("Tabela das Eleições", icon = icon("table"),
                                                              div(h5(textOutput("titulo_tab_senadores_micro")), align = "center", style = "color:black;"),
                                                              formattableOutput("tab_senadores_micro") %>% withSpinner(type = 6, color = "#555555")
                                                          )
                                                  )
                                                  
                                        ))),
                             tabPanel("Mesorregiões", id = 'tab_senador_mesorregiao',
                                      br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_meso_senador', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     selectInput('escolhe_est_senador_meso', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     selectInput('escolhe_senador_meso', "Candidato:",
                                                                 choices = NULL),
                                                     #radioButtons('senador_choice_meso', "Representação:",
                                                     #              choices = c("Qual a origem dos votos?" = 'orig_vot',
                                                     #                          "Representação dos votos por mesorregião" = 'rep_vot'),
                                                     #              selected = 'rep_vot'),
                                                     awesomeRadio(inputId = 'senador_choice_meso', label = "Representação:",
                                                     			  	choices =  c("Percentual de votos por município" = 'rep_vot',
                                                     			  				 "Qual a origem dos votos?" = 'orig_vot')),
                                                     bookmarkButton(id = "bookmark10",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                tabsetPanel(type = 'tabs',
                                                        tabPanel("Mapa das Eleições", icon = icon("map"), br(),
                                                              div(h5(textOutput("titulo_mapa_senadores_meso")), align = "center", style = "color:black;"),
                                                              leafletOutput("mapa_senadores_meso") %>% withSpinner(type = 6, color = "#555555")
                                                          ),
                                                        tabPanel("Tabela das Eleições", icon = icon("table"),
                                                              div(h5(textOutput("titulo_tab_senadores_meso")), align = "center", style = "color:black;"),
                                                              formattableOutput("tab_senadores_meso") %>% withSpinner(type = 6, color = "#555555")
                                                          )
                                                  )
                                                  
                                        )))
                       )),
        tabPanel("Governador", id = 'tab_governador',
                h4("Eleições Gerais para Governador", align = "center"), 
                 tabsetPanel(type = 'tabs', id = 'tab_set_governadores',
                       tabPanel("Estado", id = 'tab_governador_estado',
                                  br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_gov_est', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                    #radioButtons('gov_turno_est', "Turno:",
                                                    #               choices = c("1º Turno" = 'turno_1',
                                                    #                           "2º Turno" = 'turno_2')),
                                                    awesomeRadio(inputId = 'gov_turno_est', label = "Turno:",
                                                     			  choices = c("1º Turno" = 'turno_1',
                                                     			  			  "2º Turno" = 'turno_2')),
                                                    selectInput('escolhe_est_gov_est', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     bookmarkButton(id = "bookmark11",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9,
                                                tabsetPanel(type = 'tabs',
                                                            tabPanel("Distribuição dos Votos",icon = icon("database"),
                                                                     br(),
                                                                     uiOutput("tree_gov_final_est") %>% withSpinner(type = 6, color = "#555555")),
                                                            tabPanel("Votação dos Candidatos",icon = icon("bar-chart"),
                                                                     br(),
                                                                     plotlyOutput("grafico_gov_est") %>% withSpinner(type = 6, color = "#555555"))                                                        
                                                            )))),
                       tabPanel("Municípios", id = 'tab_governador_municipio',
                                     br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_mun_gov', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     #radioButtons('gov_turno_mun', "Turno:",
                                                     #              choices = c("1º Turno" = 'turno_1',
                                                     #                          "2º Turno" = 'turno_2')),
                                                     awesomeRadio(inputId = 'gov_turno_mun', label = "Turno:",
                                                     			  choices = c("1º Turno" = 'turno_1',
                                                     			  			  "2º Turno" = 'turno_2')),
                                                     selectInput('escolhe_est_gov_mun', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     selectInput('escolhe_gov_mun', "Candidato:",
                                                                 choices = NULL),
                                                     #radioButtons('gov_choice_mun', "Representação:",
                                                     #              choices = c("Qual a origem dos votos?" = 'orig_vot',
                                                     #                          "Representação dos votos por município" = 'rep_vot'),
                                                     #              selected = 'rep_vot'),
                                                     awesomeRadio(inputId = 'gov_choice_mun', label = "Representação:",
                                                     			  	choices =  c("Percentual de votos por município" = 'rep_vot',
                                                     			  				 "Qual a origem dos votos?" = 'orig_vot')),
                                                     bookmarkButton(id = "bookmark12",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                tabsetPanel(type = 'tabs',
                                                        tabPanel("Mapa das Eleições", icon = icon("map"), br(),
                                                              div(h5(textOutput("titulo_mapa_gov_mun")), align = "center", style = "color:black;"),
                                                              leafletOutput("mapa_gov_mun") %>% withSpinner(type = 6, color = "#555555")
                                                          ),
                                                        tabPanel("Tabela das Eleições", icon = icon("table"),
                                                              div(h5(textOutput("titulo_tab_gov_mun")), align = "center", style = "color:black;"),
                                                              formattableOutput("tab_gov_mun") %>% withSpinner(type = 6, color = "#555555")
                                                          )
                                                  )
                                                  
                                        ))),
                       tabPanel("Microrregiões", id = 'tab_governador_microrregiao',
                                     br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_micro_gov', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     #radioButtons('gov_turno_micro', "Turno:",
                                                     #              choices = c("1º Turno" = 'turno_1',
                                                     #                          "2º Turno" = 'turno_2')),
                                                     awesomeRadio(inputId = 'gov_turno_micro', label = "Turno:",
                                                     			  choices = c("1º Turno" = 'turno_1',
                                                     			  			  "2º Turno" = 'turno_2')),
                                                     selectInput('escolhe_est_gov_micro', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     selectInput('escolhe_gov_micro', "Candidato:",
                                                                 choices = NULL),
                                                     #radioButtons('gov_choice_micro', "Representação:",
                                                     #              choices = c("Qual a origem dos votos?" = 'orig_vot',
                                                     #                          "Representação dos votos por microrregião" = 'rep_vot'),
                                                     #              selected = 'rep_vot'),
                                                     awesomeRadio(inputId = 'gov_choice_micro', label = "Representação:",
                                                     			  	choices =  c("Percentual de votos por município" = 'rep_vot',
                                                     			  				 "Qual a origem dos votos?" = 'orig_vot')),
                                                     bookmarkButton(id = "bookmark13",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                tabsetPanel(type = 'tabs',
                                                        tabPanel("Mapa das Eleições", icon = icon("map"), br(),
                                                              div(h5(textOutput("titulo_mapa_gov_micro")), align = "center", style = "color:black;"),
                                                              leafletOutput("mapa_gov_micro") %>% withSpinner(type = 6, color = "#555555")
                                                          ),
                                                        tabPanel("Tabela das Eleições", icon = icon("table"),
                                                              div(h5(textOutput("titulo_tab_gov_micro")), align = "center", style = "color:black;"),
                                                              formattableOutput("tab_gov_micro") %>% withSpinner(type = 6, color = "#555555")
                                                          )
                                                  )
                                                  
                                        ))),
                       tabPanel("Mesorregiões", id = 'tab_governador_mesorregiao',
                                     br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_meso_gov', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     #radioButtons('gov_turno_meso', "Turno;",
                                                     #              choices = c("1º Turno" = 'turno_1',
                                                     #                          "2º Turno" = 'turno_2')),
                                                     awesomeRadio(inputId = 'gov_turno_meso', label = "Turno:",
                                                     			  choices = c("1º Turno" = 'turno_1',
                                                     			  			  "2º Turno" = 'turno_2')),
                                                     selectInput('escolhe_est_gov_meso', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     selectInput('escolhe_gov_meso', "Candidato:",
                                                                 choices = NULL),
                                                     #radioButtons('gov_choice_meso', "Representação:",
                                                     #              choices = c("Qual a origem dos votos?" = 'orig_vot',
                                                     #                          "Representação dos votos por mesorregião" = 'rep_vot'),
                                                     #              selected = 'rep_vot'),
                                                     awesomeRadio(inputId = 'gov_choice_meso', label = "Representação:",
                                                     			  	choices =  c("Percentual de votos por município" = 'rep_vot',
                                                     			  				 "Qual a origem dos votos?" = 'orig_vot')),
                                                     bookmarkButton(id = "bookmark14",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                tabsetPanel(type = 'tabs',
                                                        tabPanel("Mapa das Eleições", icon = icon("map"), br(),
                                                              div(h5(textOutput("titulo_mapa_gov_meso")), align = "center", style = "color:black;"),
                                                              leafletOutput("mapa_gov_meso") %>% withSpinner(type = 6, color = "#555555")
                                                          ),
                                                        tabPanel("Tabela das Eleições", icon = icon("table"),
                                                              div(h5(textOutput("titulo_tab_gov_meso")), align = "center", style = "color:black;"),
                                                              formattableOutput("tab_gov_meso") %>% withSpinner(type = 6, color = "#555555")
                                                          )
                                                  )
                                                  
                                        )))

                       )),
        tabPanel("Deputado Federal", id = 'tab_deputado_federal',
                h4("Eleições Gerais para Deputado Federal", align = "center"), 
                 tabsetPanel(type = 'tabs', id = 'tab_set_deputados_federais',
                       tabPanel("Estado", id = 'tab_deputado_federal_estado',
                                  br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_dep_fed_est', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                    selectInput('escolhe_est_dep_fed_est', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     bookmarkButton(id = "bookmark15",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9,
                                                tabsetPanel(type = 'tabs',
                                                            tabPanel("Distribuição dos Votos",icon = icon("database"),
                                                                     br(),
                                                                     uiOutput("tree_dep_fed_final_est") %>% withSpinner(type = 6, color = "#555555")),
                                                            tabPanel("Votação dos Candidatos",icon = icon("bar-chart"),
                                                                     br(),
                                                                     plotlyOutput("grafico_dep_fed_est") %>% withSpinner(type = 6, color = "#555555"))                                                      
                                                            )))),
                       tabPanel("Municípios", id = 'tab_deputado_federal_municipio',
                                     br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_mun_dep_fed', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     selectInput('escolhe_est_dep_fed', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     selectInput('escolhe_cand_dep_fed', "Candidato:",
                                                                  choices = NULL),
                                                     #radioButtons('dep_fed_map_choice_mun', "Representação:",
                                                     #              choices = c("Qual a origem dos votos?" = 'orig_vot',
                                                     #                          "Representação dos votos por município" = 'rep_vot'),
                                                     #              selected = 'rep_vot'),
                                                     awesomeRadio(inputId = 'dep_fed_map_choice_mun', label = "Representação:",
                                                     			  	choices =  c("Percentual de votos por município" = 'rep_vot',
                                                     			  				 "Qual a origem dos votos?" = 'orig_vot')),
                                                     bookmarkButton(id = "bookmark16",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                tabsetPanel(type = 'tabs',
                                                        tabPanel("Mapa das Eleições", icon = icon("map"), br(),
                                                              div(h5(textOutput("titulo_mapa_dep_fed_mun")), align = "center", style = "color:black;"),
                                                              leafletOutput("mapa_dep_fed_mun") %>% withSpinner(type = 6, color = "#555555")
                                                          ),
                                                        tabPanel("Tabela das Eleições", icon = icon("table"),
                                                              div(h5(textOutput("titulo_tab_dep_fed_mun")), align = "center", style = "color:black;"),
                                                              formattableOutput("tab_dep_fed_mun") %>% withSpinner(type = 6, color = "#555555")
                                                          )
                                                  )
                                                  
                                        ))),
                             tabPanel("Microrregiões", id = 'tab_deputado_federal_microrregiao',
                                      br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_micro_dep_fed', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     selectInput('escolhe_est_dep_fed_micro', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     selectInput('escolhe_cand_dep_fed_micro', "Candidato:",
                                                                  choices = NULL),
                                                     #radioButtons('dep_fed_map_choice_micro', "Representação:",
                                                     #              choices = c("Qual a origem dos votos?" = 'orig_vot',
                                                     #                          "Representação dos votos por microrregião" = 'rep_vot'),
                                                     #              selected = 'rep_vot'),
                                                     awesomeRadio(inputId = 'dep_fed_map_choice_micro', label = "Representação:",
                                                     			  	choices =  c("Percentual de votos por município" = 'rep_vot',
                                                     			  				 "Qual a origem dos votos?" = 'orig_vot')),
                                                     bookmarkButton(id = "bookmark17",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                tabsetPanel(type = 'tabs',
                                                        tabPanel("Mapa das Eleições", icon = icon("map"), br(),
                                                              div(h5(textOutput("titulo_mapa_dep_fed_micro")), align = "center", style = "color:black;"),
                                                              leafletOutput("mapa_dep_fed_micro") %>% withSpinner(type = 6, color = "#555555")
                                                          ),
                                                        tabPanel("Tabela das Eleições", icon = icon("table"),
                                                              div(h5(textOutput("titulo_tab_dep_fed_micro")), align = "center", style = "color:black;"),
                                                              formattableOutput("tab_dep_fed_micro") %>% withSpinner(type = 6, color = "#555555")
                                                          )
                                                  )
                                                  
                                        ))),
                             tabPanel("Mesorregiões", id = 'tab_deputado_federal_mesorregiao',
                                      br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_meso_dep_fed', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     selectInput('escolhe_est_dep_fed_meso', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     selectInput('escolhe_cand_dep_fed_meso', "Candidato:",
                                                                  choices = NULL),
                                                     #radioButtons('dep_fed_map_choice_meso', "Representação:",
                                                     #              choices = c("Qual a origem dos votos?" = 'orig_vot',
                                                     #                          "Representação dos votos por mesorregião" = 'rep_vot'),
                                                     #              selected = 'rep_vot'),
                                                     awesomeRadio(inputId = 'dep_fed_map_choice_meso', label = "Representação:",
                                                     			  	choices =  c("Percentual de votos por município" = 'rep_vot',
                                                     			  				 "Qual a origem dos votos?" = 'orig_vot')),
                                                     bookmarkButton(id = "bookmark18",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                tabsetPanel(type = 'tabs',
                                                        tabPanel("Mapa das Eleições", icon = icon("map"), br(),
                                                              div(h5(textOutput("titulo_mapa_dep_fed_meso")), align = "center", style = "color:black;"),
                                                              leafletOutput("mapa_dep_fed_meso") %>% withSpinner(type = 6, color = "#555555")
                                                          ),
                                                        tabPanel("Tabela das Eleições", icon = icon("table"),
                                                              div(h5(textOutput("titulo_tab_dep_fed_meso")), align = "center", style = "color:black;"),
                                                              formattableOutput("tab_dep_fed_meso") %>% withSpinner(type = 6, color = "#555555")
                                                          )
                                                  )
                                                  
                                        )))
                       )),
        tabPanel("Presidente", id = 'tab_presidente',
                h4("Eleições Gerais para Presidente", align = "center"), 
                 tabsetPanel(type = 'tabs', id = 'tab_set_presidentes',
                       tabPanel("País", id = 'tab_presidente_pais',
                                  br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_pres_pais', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     #radioButtons('pres_turno_pais', "Turno:",
                                                     #              choices = c("1º Turno" = 'turno_1',
                                                     #                          "2º Turno" = 'turno_2')),
                                                     awesomeRadio(inputId = 'pres_turno_pais', label = "Turno:",
                                                     			  choices = c("1º Turno" = 'turno_1',
                                                     			  			  "2º Turno" = 'turno_2')),
                                                     bookmarkButton(id = "bookmark19",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9,
                                                tabsetPanel(type = 'tabs',
                                                            tabPanel("Distribuição dos Votos",icon = icon("database"),
                                                                     br(),
                                                                     uiOutput("tree_pres_final_pais") %>% withSpinner(type = 6, color = "#555555")),
                                                            tabPanel("Votação dos Candidatos",icon = icon("bar-chart"),
                                                                     br(),
                                                                     plotlyOutput("grafico_pres_pais") %>% withSpinner(type = 6, color = "#555555"))                                                         
                                                            )))),
                       tabPanel("Estados", id = 'tab_presidente_estado',
                                  br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_pres_est', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     #radioButtons('pres_turno_est', "Turno:",
                                                     #              choices = c("1º Turno" = 'turno_1',
                                                     #                          "2º Turno" = 'turno_2')),
                                                     awesomeRadio(inputId = 'pres_turno_est', label = "Turno:",
                                                     			  choices = c("1º Turno" = 'turno_1',
                                                     			  			  "2º Turno" = 'turno_2')),
                                                     selectInput('escolhe_pres_est', "Candidato:",
                                                                 choices = NULL),
                                                     #radioButtons('pres_choice_est', "Representação",
                                                     #              choices = c("Qual a origem dos votos?" = 'orig_vot',
                                                     #                          "Representação dos votos por município" = 'rep_vot'),
                                                     #              selected = 'rep_vot'),
                                                     awesomeRadio(inputId = 'pres_choice_est', label = "Representação:",
                                                     			  	choices =  c("Percentual de votos por município" = 'rep_vot',
                                                     			  				 "Qual a origem dos votos?" = 'orig_vot')),
                                                     bookmarkButton(id = "bookmark20",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                tabsetPanel(type = 'tabs',
                                                        tabPanel("Mapa das Eleições", icon = icon("map"), br(),
                                                              div(h5(textOutput("titulo_mapa_pres_est")), align = "center", style = "color:black;"),
                                                              leafletOutput("mapa_pres_est") %>% withSpinner(type = 6, color = "#555555")
                                                          ),
                                                        tabPanel("Tabela das Eleições", icon = icon("table"),
                                                              div(h5(textOutput("titulo_tab_pres_est")), align = "center", style = "color:black;"),
                                                              formattableOutput("tab_pres_est") %>% withSpinner(type = 6, color = "#555555")
                                                          )
                                                  )
                                                  
                                        ))),
                       tabPanel("Municípios", id = 'tab_presidente_municipio',
                                     br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_mun_pres', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     #radioButtons('pres_turno_mun', "Turno:",
                                                     #              choices = c("1º Turno" = 'turno_1',
                                                     #                          "2º Turno" = 'turno_2')),
                                                     awesomeRadio(inputId = 'pres_turno_mun', label = "Turno:",
                                                     			  choices = c("1º Turno" = 'turno_1',
                                                     			  			  "2º Turno" = 'turno_2')),
                                                     selectInput('escolhe_est_pres_mun', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     selectInput('escolhe_pres_mun', "Candidato:",
                                                                 choices = NULL),
                                                     #radioButtons('pres_choice_mun', "Representação:",
                                                     #              choices = c("Qual a origem dos votos?" = 'orig_vot',
                                                     #                          "Representação dos votos por município" = 'rep_vot'),
                                                     #              selected = 'rep_vot'),
                                                     awesomeRadio(inputId = 'pres_choice_mun', label = "Representação:",
                                                     			  	choices =  c("Percentual de votos por município" = 'rep_vot',
                                                     			  				 "Qual a origem dos votos?" = 'orig_vot')),
                                                     bookmarkButton(id = "bookmark21",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                tabsetPanel(type = 'tabs',
                                                        tabPanel("Mapa das Eleições", icon = icon("map"), br(),
                                                              div(h5(textOutput("titulo_mapa_pres_mun")), align = "center", style = "color:black;"),
                                                              leafletOutput("mapa_pres_mun") %>% withSpinner(type = 6, color = "#555555")
                                                          ),
                                                        tabPanel("Tabela das Eleições", icon = icon("table"),
                                                              div(h5(textOutput("titulo_tab_pres_mun")), align = "center", style = "color:black;"),
                                                              formattableOutput("tab_pres_mun") %>% withSpinner(type = 6, color = "#555555")
                                                          )
                                                  )
                                                  
                                        ))),
                       tabPanel("Microrregiões", id = 'tab_presidente_microrregiao',
                                     br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_micro_pres', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     #radioButtons('pres_turno_micro', "Turno:",
                                                     #              choices = c("1º Turno" = 'turno_1',
                                                     #                          "2º Turno" = 'turno_2')),
                                                     awesomeRadio(inputId = 'pres_turno_micro', label = "Turno:",
                                                     			  choices = c("1º Turno" = 'turno_1',
                                                     			  			  "2º Turno" = 'turno_2')),
                                                     selectInput('escolhe_est_pres_micro', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     selectInput('escolhe_pres_micro', "Candidato:",
                                                                 choices = NULL),
                                                     #radioButtons('pres_choice_micro', "Representação:",
                                                     #              choices = c("Qual a origem dos votos?" = 'orig_vot',
                                                     #                          "Representação dos votos por microrregião" = 'rep_vot'),
                                                     #              selected = 'rep_vot'),
                                                     awesomeRadio(inputId = 'pres_choice_micro', label = "Representação:",
                                                     			  	choices =  c("Percentual de votos por município" = 'rep_vot',
                                                     			  				 "Qual a origem dos votos?" = 'orig_vot')),
                                                     bookmarkButton(id = "bookmark22",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                tabsetPanel(type = 'tabs',
                                                        tabPanel("Mapa das Eleições", icon = icon("map"), br(),
                                                              div(h5(textOutput("titulo_mapa_pres_micro")), align = "center", style = "color:black;"),
                                                              leafletOutput("mapa_pres_micro") %>% withSpinner(type = 6, color = "#555555")
                                                          ),
                                                        tabPanel("Tabela das Eleições", icon = icon("table"),
                                                              div(h5(textOutput("titulo_tab_pres_micro")), align = "center", style = "color:black;"),
                                                              formattableOutput("tab_pres_micro") %>% withSpinner(type = 6, color = "#555555")
                                                          )
                                                  )
                                                  
                                        ))),
                       tabPanel("Mesorregiões", id = 'tab_presidente_mesorregiao',
                                     br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                     sliderInput('ano_meso_pres', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     #radioButtons('pres_turno_meso', "Turno:",
                                                     #              choices = c("1º Turno" = 'turno_1',
                                                     #                          "2º Turno" = 'turno_2')),
                                                     awesomeRadio(inputId = 'pres_turno_meso', label = "Turno:",
                                                     			  choices = c("1º Turno" = 'turno_1',
                                                     			  			  "2º Turno" = 'turno_2')),
                                                     selectInput('escolhe_est_pres_meso', "Estado:",
                                                                  unique(tse_data_ui$NOME_UF),
                                                                  selected = "São Paulo"),
                                                     selectInput('escolhe_pres_meso', "Candidato:",
                                                                 choices = NULL),
                                                     #radioButtons('pres_choice_meso', "Representação:",
                                                     #              choices = c("Qual a origem dos votos?" = 'orig_vot',
                                                     #                          "Representação dos votos por mesorregião" = 'rep_vot'),
                                                     #              selected = 'rep_vot'),
                                                     awesomeRadio(inputId = 'pres_choice_meso', label = "Representação:",
                                                     			  	choices =  c("Percentual de votos por município" = 'rep_vot',
                                                     			  				 "Qual a origem dos votos?" = 'orig_vot')),
                                                     bookmarkButton(id = "bookmark23",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                tabsetPanel(type = 'tabs',
                                                        tabPanel("Mapa das Eleições", icon = icon("map"), br(),
                                                              div(h5(textOutput("titulo_mapa_pres_meso")), align = "center", style = "color:black;"),
                                                              leafletOutput("mapa_pres_meso") %>% withSpinner(type = 6, color = "#555555")
                                                          ),
                                                        tabPanel("Tabela das Eleições", icon = icon("table"),
                                                              div(h5(textOutput("titulo_tab_pres_meso")), align = "center", style = "color:black;"),
                                                              formattableOutput("tab_pres_meso") %>% withSpinner(type = 6, color = "#555555")
                                                          )
                                                  )
                                                  
                                        )))
                       ))
        
        ),
        tabPanel(id = "markov_chain","Mapas de Transição", icon = icon("map"),
                                  h4("Mapa de Transição das Eleições Presidenciais", align = "center"), 
                                  br(),
                                      sidebarLayout(
                                        sidebarPanel(width = 3,
                                                    radioGroupButtons(
                                                        inputId = "checkbox_markov_pres", label = "Escolha uma regionalização :", 
                                                        choices = c("Mesorregiões" = 'markov_meso_choice', 
                                                                    "Microrregiões" = 'markov_micro_choice',
                                                                    "Municípios" = 'markov_mun_choice'), 
                                                        #status = "primary", 
                                                        size = "xs", 
                                                        justified = TRUE),
                                                     sliderInput('ano_markov_pais', "Ano:",
                                                                 min = 1998,
                                                                 max = 2014,
                                                                 value = 2014,
                                                                 step = 4,
                                                                 sep = ""),
                                                     conditionalPanel(condition = 'input.checkbox_markov_pres == "markov_mun_choice"',
                                                     				  selectInput('markov_state_choice', "Estado:",
                                                     				  			 unique(tse_data_ui$NOME_UF),
                                                     				  			 selected = "São Paulo")),
                                                     selectInput('markov_escolhe_presidente', "Candidato:",
                                                                 choices = NULL),
                                                     div(h6("As opções de presidente acima são definidas apenas pelos
                                                             candidatos que avançaram para o 2º turno."), align = "center", style = "color:light-grey;"),
                                                     bookmarkButton(id = "bookmark24",
                                                                    label = "Compartilhe...",
                                                                    icon = icon("share-alt"),
                                                                    title = "Compartilhe essa informação!")),
                                      mainPanel(width = 9 ,
                                                leafletOutput("mapa_pres_markov") %>% withSpinner(type = 6, color = "#555555")
                                                ))),
            tabPanel(id = "about_me", "Sobre", icon = icon("info-circle"),
            	div(
            	h3("Sobre", style = "color:black"),
            	p(paste0("O projeto CepespVis foi desenvolvido por Luis Henrique Zanandréa Paese, como partipação no 1º Desafio do CEPESP:",
            			 " Decifrando as Eleições, coordenado pelo Centro de Política e Economia do Setor Público (CEPESP) da Fundação",
            			 " Getúlio Vargas (FGV).")),
            	p(paste0("O desenvolvimento da presente aplicação se deu completamente com o uso de softwares de código aberto, sendo ",
            		     "utilizados para o desenvolvimento do mesmo o software estatístico"), a("R", href = "https://www.r-project.org/"),
            			 paste0(", bem como a interface interativa "),a("Shiny", href = "https://shiny.rstudio.com/"),
            			 paste0(". Todos os demais pacotes e ferramentas utilizadas na ",
            		     "formulação do aplicativo também se enquadram na categoria open-source.")),
            	tags$ul(
            		tags$li("Desenvolvido por: Luis Henrique Zanandréa Paese"),
            		tags$li("E-mail: ", a(href = "mailto:paeselab@gmail.com", "paeselab@gmail.com")),
            		tags$li(a("LinkedIn", icon("linkedin-square"), href = "https://www.linkedin.com/in/lhzpaese", target = "_blank")),
            		tags$li(a("Facebook", icon("facebook-official"), href = "https://www.facebook.com/luishzp", target = "_blank")),
            		tags$li("Telefone para Contato: (54) 98404-9404")
            		),
            	h3("Funcionamento da Plataforma", style = "color:black"),
            	h5("Eleições Municipais", style = "color:black"),
            	p(paste0("A aba de eleições municipais traz dados referentes as eleições dos anos de 2000, 2004, 2008, 2012 e 2016, ",
            		     "cuja menor observação são os municípios do Brasil. Contendo dados das eleições para Vereadores e para Prefeitos, ",
            		     "a aba traz através de um treemap, a visualização proporcional, como cada Coligação, Partido ou Candidato teve seus ",
            		     "votos distribuidos em uma determinada eleição. Além disso, a subseção de Vereadores traz a opção de conhecimento do",
            		     " Quociente Eleitoral, medida usada pelo TSE para atribuir aos candidatos a eleição através de",
            		     " Quociente Partidário, ou através de Média.")),
            	h5("Eleições Gerais", sytle = "color:black"),
            	p(paste0("A aba de eleições gerais traz dados referentes as eleições dos anos de 1998, 2002, 2006, 2010 e 2014. 
            			 Além da visualização dos dados relacionados aos candidatos em nível estadual (e nacional no caso dos 
            			 candidatos a presidente), essa aba contém mapas interativos que podem mostrar tanto a representação dos votos 
            			 de um candidato, em relação ao total de uma determinada unidade geográfica, quanto qual a origem dos votos de 
            			 um determinado candidato. Isso permite, além de uma visualização para os municípios, também uma visualizãção 
            			 para outras agregações regionais definidas pelo IBGE (Instituto Brasileiro de Geografia e Estatística), como 
            			 Microrregiões e Mesorregiões."),
            		br(),
            		paste0("A visualização de dados também estende-se ao âmbito mais objetivo, de observar onde um determinado candidato conquistou
						 mais votos, através de tabelas que podem ser ordenadas tanto pela representação dos votos de um candidato sobre os votos
						  de uma unidade geográfica, quanto pela representação dos votos sobre o total do próprio candidato."),
            		br(),
            		paste0("Todas as visualizações descritas acima estão presentes para Deputados Estaduais, Senadores, Governadores,
						 Deputados Federais e Presidentes. ")),
            	h5("Mapas de Transição", style = "color:black"),
            	p(paste0("Os mapas de transição que podem ser gerados através da ferramenta estão disponíveis apenas para as eleições para presidentes,
            			 e exclusivamente aos candidatos que concorrem ao segundo turno de cada eleição. Essa visualização permite visualizar, para cada 
            			 um dos anos eleitorais, como se deu a transição dos votos do 1º para o 2º turno, mostrando de uma forma objetiva se um candidato 
            			 manteve sua posição em uma determinada regionalização entre um turno e outro, ou se ganhou/perdeu votos.")),
            	h5("Compartilhe as informações", style = "color:black"),
            	p(paste0("Cada aba possui um botão de compartilhamento, que gera um link exclusivo para a visualização do usuário, permitindo assim que cada
            			 pessoa possa encontrar a informação que deseja, e repassá-la para quem interessar."))

            	), style = "margin:15px") 
        )   
  )
})